services:

  vantage6-server:
    image: localhost:5000/infrastructure/server:local
    ports:
      - "7601:7601"
    depends_on:
      - database
    volumes:
      - ./configs/postgress.yaml:/mnt/config.yaml
    command: [
      "uwsgi",
      "--http", ":7601",
      "--gevent", "1000",
      "--http-websockets",
      "--http-chunked-input",
      "--http-keepalive",
      "--post-buffering", "0",
      "--master",
      "--callable", "app",
      "--disable-logging",
      "--wsgi-file", "/vantage6/vantage6-server/vantage6/server/wsgi.py",
      "--pyargv", "/mnt/config.yaml"
    ]

  ui:
    image: localhost:5000/infrastructure/ui:latest
    ports:
      - "8000:80"
    environment:
      - SERVER_URL=http://localhost:7601
      - API_PATH=/api
    depends_on:
      - vantage6-server


  database:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme

  local-registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"


secrets:
  hospital_v6_secrets:
    file: ./.secrets/hospital_v6.env
  azure_client_secret:
    file: ./.secrets/azure_client_secret.txt
  azure_client_id:
    file: ./.secrets/azure_client_id.txt
  azure_tenant_id:
    file: ./.secrets/azure_tenant_id.txt
  azure_blob_account_url:
    file: ./.secrets/azure_blob_account_url.txt
  docker_registry_url:
    file: ./.secrets/docker_registry_url.txt
  docker_registry_username:
    file: ./.secrets/docker_registry_username.txt
  docker_registry_password:
    file: ./.secrets/docker_registry_password.txt